spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/doubi?useUnicode=true&useSSL=false&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: root312
    hikari:
      # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQL异常
      connection-timeout: 30000
      # 最小连接数
      minimum-idle: 10
      # 最大连接数
      maximum-pool-size: 20
      # 自动提交
      auto-commit: true
      # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      idle-timeout: 600000
      # 连接池名字
      pool-name: DateSourceHikariCP
      # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟
      max-lifetime: 1800000
      connection-test-query: SELECT 1


  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10s
    ssl: false
    lettuce:
      pool:
        max-idle: 10
        max-active: 20
        max-wait: -1
        min-idle: 0
